### PR TITLE
Milestone Three

### PR DESCRIPTION
**Pull request by s0kil**
Major changes since [milestone two](https://github.com/danielsokil/Ruby_Tic_Tac_Toe/pull/2):
- We introduced a [Textual Interface](https://github.com/danielsokil/Ruby_Tic_Tac_Toe/pull/6)
- Finished the Game Logic in these PR's, #5 and #7 

How to run:
- clone repo, and checkout this branch.
- `bundle install`
- `bin/main`

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

Nice work on this.
However, let's fix this

- [x] In the scenario as shown in the screenshot below, your game signals a winner, which shouldn't be. Kindly fix it.
ice_screenshot_20200803-213334

- [x]  No puts or print should be in files in the `lib` folder. Kindly remove all puts and print statements found in files in its directory and subdirectory.

- [x] After the game ends ctrl+c doesn't work to exit the game.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey team  :wave:
-
Good job with the changes! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
- [x] The game freezes upon the initial run. No progress after this part and the player moves cant be seen on the board. Ket's work on this glitch.
- [x] There should be no inline comments left after the previous milestone. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/no_comment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by trekab — COMMENTED** [review]
Please work on the feedback from the last T.S.E before you submit another code review request!

_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by s0kil** [comment]
All the mentioned problems have been fixed, except terminal resizing on Windows OS, which is not a requirement for this project.

**Review by trekab — APPROVED** [review]
## Approved! :tada: 
Hi @s0kil and @wrakc! Well done! The game is functional and your UI is impressive. There are some issues with your code though. __[OPTIONAL]__ Your use of modules doesn't follow the industry preferred standard. Consider [this](http://ruby-for-beginners.rubymonstas.org/advanced/modules.html) article about modules.

_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by s0kil** [comment]
@trekab Thank You, would be great if you could elaborate on the issue with our use of modules.

**Review by trekab — COMMENTED** [review]
Everything in your code has been placed inside the `TicTacToe` module. This is unnecessary. You should consider working with `mixins` if you are interested in sharing module methods within your classes. Encapsulating the Game class inside the TicTacToe module is completely redundant.

**Comment by s0kil** [comment]
That's a good point, will think about it.

**Pull request merged**
